# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6607782a4247f3603e15e4b7c96136e2b4bf2a99041b66aa53efd15be76c4220682f8f65d9bd5bcca80bcf8cb3c72ca149b61b09866634f822391ff0b66187f1

test:
  secret_key_base: 11736fc5ff2fc46a2d49f5875ded69a45f660c73000b2a44085ce10122ab66d259868f4fcf44d778b7f1d30c147f3c8fe76bda063064cde6ebaeaf4c13d7da3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
